# vae config
model:
  latent_size: 64
  seq_len: 16
  vae_latent_size: 64
  num_mixtures: 5
  rnn_rew_loss_weight: 9
seed: 42
epoch: 100
batch_size: 4096
lr: 3e-5
action_shape: 8
obs_shape: 60
