# rnn config
model:
  latent_size: 64
  seq_len: 128
  vae_latent_size: 64
  num_mixtures: 5
#  rnn_rew_loss_weight: 9
#  rnn_seq_len: 1000
seed: 42
epoch: 100
<<<<<<< HEAD
batch_size: 1024
lr: 0.001
=======
batch_size: 4096
lr: 0.0003
>>>>>>> 07c96e602b11beb10d1557eaa97a0afafc5457e5
action_shape: 8
obs_shape: 60
