# rnn config
model:
  latent_size: 64
  seq_len: 128
  vae_latent_size: 64
  num_mixtures: 5
  rnn_size: 256
seed: 42
epoch: 100
batch_size: 1024
lr: 0.0003
action_shape: 8
obs_shape: 60
