#setting of original env
action_shape: 8
obs_shape: 60
# training params
seed: 42

model:
  vae:
    hidden_size: 64
  rnn:
    latent_size: 64
#      vae_latent_size: 64
    num_mixtures: 5
    rnn_size: 256
    seq_len: 32

train:
  vae:
    batch_size: 16384 #4096
    lr: 0.3
    epoch: 200

  rnn:
    batch_size: 4096
    lr: 0.0001
    epoch: 100

sim_env:
  vae_path: /data/yuanxi20/tmpwm/vae_44.pth
  mdrnn_path: /data/yuanxi20/tmpwm/mdrnn.pth


